### ISSUE TITLE
ModuleNotFoundError: No module named 'dataclasses'

### ISSUE THREAD

**Issue by Agi-dev** [Bogdanp/dramatiq_dashboard#11]
macOs Catalina 10.15.2
Dramatiq 1.7.0

I've copy/past `Run the dashboard on top of an existing WSGI app`.

I started server with `python manage.py runserver`
and it fails with:
```
System check identified no issues (0 silenced).
January 14, 2020 - 14:07:44
Django version 2.2.8, using settings 'myapp.settings.local'
Starting development server at http://myapp.local:8000/
Quit the server with CONTROL-C.
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/francois/Workspaces/python/myapp/venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 45, in get_internal_wsgi_application
    return import_string(app_path)
  File "/Users/francois/Workspaces/python/myapp/venv/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/Users/francois/Workspaces/python/myapp/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/francois/Workspaces/python/myapp/myapp/wsgi.py", line 13, in <module>
    import dramatiq_dashboard
  File "/Users/francois/Workspaces/python/myapp/venv/lib/python3.6/site-packages/dramatiq_dashboard/__init__.py", line 1, in <module>
    from .application import DashboardApp
  File "/Users/francois/Workspaces/python/myapp/venv/lib/python3.6/site-packages/dramatiq_dashboard/application.py", line 7, in <module>
    from .csrf import csrf_protect, render_csrf_token
  File "/Users/francois/Workspaces/python/myapp/venv/lib/python3.6/site-packages/dramatiq_dashboard/csrf.py", line 5, in <module>
    from .http import HTTP_403, make_response
  File "/Users/francois/Workspaces/python/myapp/venv/lib/python3.6/site-packages/dramatiq_dashboard/http.py", line 2, in <module>
    from dataclasses import dataclass, field
ModuleNotFoundError: No module named 'dataclasses'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/francois/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/francois/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/francois/Workspaces/python/myapp/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Users/francois/Workspaces/python/myapp/venv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 137, in inner_run
    handler = self.get_handler(*args, **options)
  File "/Users/francois/Workspaces/python/myapp/venv/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super().get_handler(*args, **options)
  File "/Users/francois/Workspaces/python/myapp/venv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 64, in get_handler
    return get_internal_wsgi_application()
  File "/Users/francois/Workspaces/python/myapp/venv/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 50, in get_internal_wsgi_application
    ) from err
django.core.exceptions.ImproperlyConfigured: WSGI application 'myapp.wsgi.application' could not be loaded; Error importing module.
```

**Comment by Agi-dev** [comment]
I've tried with `Run the dashboard as a standalone webserver` for same result.

**Comment by vkatochka** [comment]
run
> pip install dataclasses

https://pypi.org/project/dataclasses/

**Comment by Agi-dev** [comment]
Ok, thanks. Is it not a missing dependency ?
