### ISSUE TITLE
Support ASGI so it can be run inside modern Django apps

### ISSUE THREAD

**Issue by pirate** [Bogdanp/dramatiq_dashboard#9]
I'm trying to do something like this in a django app:

At the end of **`myapp/urls.py:`**
```python3
if settings.ENABLE_DRAMATIQ_DASHBOARD:
    import dramatiq
    from django_wsgi.embedded_wsgi import call_wsgi_app
    from dramatiq_dashboard import DashboardApp

    app = DashboardApp(broker=dramatiq.get_broker(), prefix='')

    def dashboard_proxy_view(request, path: str):
        return call_wsgi_app(app, request, path)

    urlpatterns = [
        re_path('drama/(.*)$', dashboard_proxy_view, name='dramatiq'),
    ] + urlpatterns
```

The issue is `django_wsgi` and `DashboardApp` both expect `WSGIRequest` objects, which are different from the `ASGIRequest` objects that Django `channels` uses.

I could write a manual translation layer, but maybe you already know of a better way to run this inside a Django app that uses ASGI?

**Comment by Bogdanp** [comment]
Sorry, I haven't been keeping up with the ASGI world so I don't know if there's a better way. A manual translation layer doesn't sound bad though.

**Comment by titouanfreville** [comment]
Hello. I am trying to serve the dashboard with `uvicorn` and meet  error:

```
tasks-dashboard    | INFO:     172.18.0.1:44754 - "GET / HTTP/1.1" 500 Internal Server Error
tasks-dashboard    | ERROR:    Exception in ASGI application
tasks-dashboard    | Traceback (most recent call last):
tasks-dashboard    |   File "/home/vscode/venv/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
tasks-dashboard    |     result = await app(self.scope, self.receive, self.send)
tasks-dashboard    |   File "/home/vscode/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
tasks-dashboard    |     return await self.app(scope, receive, send)
tasks-dashboard    |   File "/home/vscode/venv/lib/python3.9/site-packages/uvicorn/middleware/asgi2.py", line 6, in __call__
tasks-dashboard    |     instance = self.app(scope)
tasks-dashboard    | TypeError: __call__() missing 1 required positional argument: 'start_response'
```

Do you think it could be linked to this issue ?
